import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { tripAPI, invoiceAPI } from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import {
  Plus, Download, CheckCircle, Loader2, FileText, X,
  Receipt, Trash2, Eye, Calendar, MapPin, Users, DollarSign,
  ArrowRight, Printer
} from 'lucide-react';

const Invoices = () => {
  const { user } = useAuth();
  const [trips, setTrips] = useState([]);
  const [selectedTrip, setSelectedTrip] = useState(null);
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [viewInv, setViewInv] = useState(null);

  useEffect(() => { loadTrips(); }, []);
  useEffect(() => { if (selectedTrip) loadInvoices(selectedTrip._id); }, [selectedTrip]);

  const loadTrips = async () => {
    try {
      const { data } = await tripAPI.getAll({});
      if (data.success && data.trips.length > 0) {
        setTrips(data.trips);
        setSelectedTrip(data.trips[0]);
      }
    } catch (e) { console.error(e); }
    finally { setLoading(false); }
  };

  const loadInvoices = async (id) => {
    try {
      const { data } = await invoiceAPI.getByTrip(id);
      if (data.success) setInvoices(data.invoices);
    } catch (e) { console.error(e); }
  };

  const handleCreate = async () => {
    if (!selectedTrip) return;
    setCreating(true);
    try {
      await invoiceAPI.create({ tripId: selectedTrip._id });
      await loadInvoices(selectedTrip._id);
    } catch (e) { console.error(e); }
    finally { setCreating(false); }
  };

  const handleMarkPaid = async (id) => {
    try {
      await invoiceAPI.markPaid(id);
      await loadInvoices(selectedTrip._id);
      if (viewInv?._id === id) setViewInv({ ...viewInv, status: 'paid', paidDate: new Date() });
    } catch (e) { console.error(e); }
  };

  const handleDelete = async (id) => {
    if (!confirm('Delete invoice?')) return;
    try {
      await invoiceAPI.delete(id);
      await loadInvoices(selectedTrip._id);
      if (viewInv?._id === id) setViewInv(null);
    } catch (e) { console.error(e); }
  };

  const handleDownload = (inv) => {
    // Generate text-based invoice for download
    const tp = selectedTrip;
    const lines = [
      `TRAVELOOP - EXPENSE INVOICE`,
      `${'='.repeat(50)}`,
      `Invoice ID: ${inv.invoiceId}`,
      `Date: ${fmt(inv.generatedDate)}`,
      `Status: ${inv.status?.toUpperCase()}`,
      ``,
      `TRIP DETAILS`,
      `Trip: ${tp?.title || 'N/A'}`,
      `Dates: ${fmt(tp?.startDate)} - ${fmt(tp?.endDate)}`,
      `Travelers: ${tp?.travelerCount || 1}`,
      `Destinations: ${tp?.destinations?.map(d => d.name).join(', ') || 'N/A'}`,
      ``,
      `${'='.repeat(50)}`,
      `ITEMS`,
      `${'─'.repeat(50)}`,
      `${'#'.padEnd(4)}${'Category'.padEnd(12)}${'Description'.padEnd(22)}${'Amount'.padStart(12)}`,
      `${'─'.repeat(50)}`,
    ];
    inv.items?.forEach((item, i) => {
      lines.push(`${String(i + 1).padEnd(4)}${(item.category || '').padEnd(12)}${(item.description || '').substring(0, 20).padEnd(22)}${('₹' + item.amount?.toLocaleString()).padStart(12)}`);
    });
    lines.push(`${'─'.repeat(50)}`);
    lines.push(`${'Subtotal'.padEnd(38)}${'₹' + inv.subtotal?.toLocaleString()}`);
    lines.push(`${'Tax (' + inv.taxRate + '%)'.padEnd(38)}${'₹' + inv.taxAmount?.toLocaleString()}`);
    lines.push(`${'Discount'.padEnd(38)}${'-₹' + (inv.discount || 0)?.toLocaleString()}`);
    lines.push(`${'='.repeat(50)}`);
    lines.push(`${'GRAND TOTAL'.padEnd(38)}${'₹' + inv.grandTotal?.toLocaleString()}`);
    lines.push(`\nGenerated by Traveloop`);

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${inv.invoiceId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const fmt = (d) => d ? new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : '';
  const tp = selectedTrip;

  // Summary stats
  const totalInvoiced = invoices.reduce((s, inv) => s + (inv.grandTotal || 0), 0);
  const totalPaid = invoices.filter(i => i.status === 'paid').reduce((s, inv) => s + (inv.grandTotal || 0), 0);
  const totalPending = invoices.filter(i => i.status !== 'paid').reduce((s, inv) => s + (inv.grandTotal || 0), 0);

  if (loading) return <div className="flex items-center justify-center py-20"><Loader2 className="w-8 h-8 text-primary-600 animate-spin" /></div>;

  return (
    <div className="animate-fade-in max-w-5xl mx-auto">
      <Link to="/dashboard/trips" className="text-sm text-slate-400 hover:text-primary-600 mb-2 inline-block">← Back to My Trips</Link>

      <div className="flex items-start justify-between mb-6">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold font-display text-slate-900">Expense Invoices</h1>
          <p className="text-slate-500 mt-1">Generate and manage trip expense invoices</p>
        </div>
        <button onClick={handleCreate} disabled={creating} className="flex items-center gap-1.5 px-4 py-2.5 bg-primary-600 text-white rounded-xl text-sm font-semibold hover:bg-primary-700 disabled:opacity-60">
          {creating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Plus className="w-4 h-4" />}Generate Invoice
        </button>
      </div>

      {/* Trip selector */}
      {trips.length > 0 && (
        <div className="mb-4">
          <select value={tp?._id || ''} onChange={e => setSelectedTrip(trips.find(t => t._id === e.target.value))} className="px-4 py-2.5 bg-white border border-slate-200 rounded-xl text-sm">
            {trips.map(t => <option key={t._id} value={t._id}>{t.title}</option>)}
          </select>
        </div>
      )}

      {/* Summary Cards */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="bg-white rounded-2xl border border-slate-100 p-5">
          <p className="text-xs text-slate-400 mb-1">Total Invoiced</p>
          <p className="text-xl font-bold text-slate-900">₹ {totalInvoiced.toLocaleString()}</p>
          <p className="text-[10px] text-slate-400 mt-1">{invoices.length} invoice{invoices.length !== 1 ? 's' : ''}</p>
        </div>
        <div className="bg-emerald-50 rounded-2xl border border-emerald-100 p-5">
          <p className="text-xs text-slate-400 mb-1">Paid</p>
          <p className="text-xl font-bold text-emerald-700">₹ {totalPaid.toLocaleString()}</p>
          <p className="text-[10px] text-emerald-500 mt-1">{invoices.filter(i => i.status === 'paid').length} paid</p>
        </div>
        <div className="bg-amber-50 rounded-2xl border border-amber-100 p-5">
          <p className="text-xs text-slate-400 mb-1">Pending</p>
          <p className="text-xl font-bold text-amber-700">₹ {totalPending.toLocaleString()}</p>
          <p className="text-[10px] text-amber-500 mt-1">{invoices.filter(i => i.status !== 'paid').length} pending</p>
        </div>
      </div>

      {/* Invoice List */}
      {invoices.length === 0 ? (
        <div className="bg-white rounded-2xl border border-slate-100 p-12 text-center">
          <Receipt className="w-16 h-16 text-slate-300 mx-auto mb-4" />
          <h3 className="text-xl font-bold text-slate-900 mb-2">No invoices yet</h3>
          <p className="text-slate-500 mb-1 text-sm">Generate an invoice from your trip expenses, hotel stays, and activities.</p>
          <p className="text-xs text-slate-400 mb-4">All costs from stops, activities, and manual expenses are auto-compiled.</p>
          <button onClick={handleCreate} disabled={creating} className="px-6 py-2.5 bg-primary-600 text-white rounded-xl text-sm font-semibold">
            <Plus className="w-4 h-4 inline mr-1" />Generate Invoice
          </button>
        </div>
      ) : (
        <div className="space-y-3">
          {invoices.map(inv => (
            <div key={inv._id} className="bg-white rounded-2xl border border-slate-100 p-5 hover:shadow-md transition-shadow">
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-4">
                  <div className={`w-12 h-12 rounded-xl flex items-center justify-center ${inv.status === 'paid' ? 'bg-emerald-50' : 'bg-primary-50'}`}>
                    <FileText className={`w-6 h-6 ${inv.status === 'paid' ? 'text-emerald-600' : 'text-primary-600'}`} />
                  </div>
                  <div>
                    <h3 className="text-sm font-bold text-slate-900">{tp?.title}</h3>
                    <div className="flex items-center gap-3 mt-0.5">
                      <span className="text-xs text-slate-400 font-mono">{inv.invoiceId}</span>
                      <span className="text-xs text-slate-400">{fmt(inv.generatedDate)}</span>
                      <span className="text-xs text-slate-400">{inv.items?.length || 0} items</span>
                    </div>
                  </div>
                </div>
                <div className="text-right flex items-center gap-3">
                  <div>
                    <span className={`px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider ${inv.status === 'paid' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>
                      {inv.status === 'paid' ? 'Paid' : 'Pending'}
                    </span>
                    <p className="text-lg font-bold text-slate-900 mt-1">₹ {inv.grandTotal?.toLocaleString()}</p>
                  </div>
                </div>
              </div>
              {/* Actions row */}
              <div className="flex items-center gap-2 mt-3 pt-3 border-t border-slate-50">
                <button onClick={() => setViewInv(inv)} className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-50 rounded-lg text-xs font-medium text-slate-600 hover:bg-slate-100"><Eye className="w-3.5 h-3.5" />View Details</button>
                <button onClick={() => handleDownload(inv)} className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-50 rounded-lg text-xs font-medium text-slate-600 hover:bg-slate-100"><Download className="w-3.5 h-3.5" />Download</button>
                {inv.status !== 'paid' && <button onClick={() => handleMarkPaid(inv._id)} className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-50 rounded-lg text-xs font-medium text-emerald-700 hover:bg-emerald-100"><CheckCircle className="w-3.5 h-3.5" />Mark Paid</button>}
                <button onClick={() => handleDelete(inv._id)} className="flex items-center gap-1.5 px-3 py-1.5 hover:bg-red-50 rounded-lg text-xs font-medium text-red-400 ml-auto"><Trash2 className="w-3.5 h-3.5" />Delete</button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* INVOICE DETAIL MODAL */}
      {viewInv && (<>
        <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50" onClick={() => setViewInv(null)} />
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto shadow-2xl animate-fade-in" onClick={e => e.stopPropagation()}>
            {/* Header */}
            <div className="flex items-center justify-between p-6 border-b border-slate-100">
              <div>
                <h3 className="text-lg font-bold text-slate-900">Invoice Details</h3>
                <p className="text-xs text-slate-400 font-mono">{viewInv.invoiceId}</p>
              </div>
              <button onClick={() => setViewInv(null)} className="p-1.5 rounded-lg hover:bg-slate-100"><X className="w-5 h-5 text-slate-400" /></button>
            </div>

            <div className="p-6">
              {/* Trip Info */}
              <div className="bg-slate-50 rounded-xl p-4 mb-5">
                <h4 className="text-sm font-bold text-slate-900 mb-2">{tp?.title}</h4>
                <div className="flex flex-wrap gap-4 text-xs text-slate-500">
                  <span className="flex items-center gap-1"><Calendar className="w-3 h-3" />{fmt(tp?.startDate)} – {fmt(tp?.endDate)}</span>
                  <span className="flex items-center gap-1"><Users className="w-3 h-3" />{tp?.travelerCount || 1} Travelers</span>
                  <span className="flex items-center gap-1"><MapPin className="w-3 h-3" />{tp?.destinations?.map(d => d.name).join(', ') || 'N/A'}</span>
                </div>
              </div>

              {/* Meta */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-5">
                <div><p className="text-[10px] text-slate-400 uppercase tracking-wider">Invoice ID</p><p className="text-sm font-mono font-bold mt-0.5">{viewInv.invoiceId}</p></div>
                <div><p className="text-[10px] text-slate-400 uppercase tracking-wider">Generated</p><p className="text-sm font-semibold mt-0.5">{fmt(viewInv.generatedDate)}</p></div>
                <div><p className="text-[10px] text-slate-400 uppercase tracking-wider">Status</p><p className={`text-sm font-bold mt-0.5 ${viewInv.status === 'paid' ? 'text-emerald-600' : 'text-amber-600'}`}>{viewInv.status === 'paid' ? '✅ Paid' : '⏳ Pending'}</p></div>
                <div><p className="text-[10px] text-slate-400 uppercase tracking-wider">Items</p><p className="text-sm font-bold mt-0.5">{viewInv.items?.length || 0}</p></div>
              </div>

              {/* Items table */}
              {viewInv.items?.length > 0 ? (
                <div className="overflow-x-auto mb-5 border border-slate-100 rounded-xl">
                  <table className="w-full text-sm">
                    <thead><tr className="bg-slate-50 text-left">
                      <th className="py-3 px-4 text-[10px] text-slate-400 font-bold uppercase tracking-wider">#</th>
                      <th className="py-3 px-4 text-[10px] text-slate-400 font-bold uppercase tracking-wider">Category</th>
                      <th className="py-3 px-4 text-[10px] text-slate-400 font-bold uppercase tracking-wider">Description</th>
                      <th className="py-3 px-4 text-[10px] text-slate-400 font-bold uppercase tracking-wider">Qty</th>
                      <th className="py-3 px-4 text-[10px] text-slate-400 font-bold uppercase tracking-wider text-right">Unit Cost</th>
                      <th className="py-3 px-4 text-[10px] text-slate-400 font-bold uppercase tracking-wider text-right">Amount</th>
                    </tr></thead>
                    <tbody>{viewInv.items.map((item, i) => (
                      <tr key={i} className="border-t border-slate-50 hover:bg-slate-50/50">
                        <td className="py-3 px-4 text-slate-400">{i + 1}</td>
                        <td className="py-3 px-4"><span className="px-2 py-0.5 bg-slate-100 rounded text-[10px] font-semibold uppercase">{item.category}</span></td>
                        <td className="py-3 px-4 text-slate-700 font-medium">{item.description}</td>
                        <td className="py-3 px-4 text-slate-500">{item.quantity}</td>
                        <td className="py-3 px-4 text-right text-slate-600">₹ {item.unitCost?.toLocaleString()}</td>
                        <td className="py-3 px-4 text-right font-bold">₹ {item.amount?.toLocaleString()}</td>
                      </tr>
                    ))}</tbody>
                  </table>
                </div>
              ) : (
                <div className="bg-slate-50 rounded-xl p-8 text-center mb-5">
                  <p className="text-sm text-slate-400">No line items. Add expenses, hotel stays, or activities to your trip to populate the invoice.</p>
                </div>
              )}

              {/* Totals */}
              <div className="bg-slate-50 rounded-xl p-4 space-y-2">
                <div className="flex justify-between text-sm"><span className="text-slate-500">Subtotal</span><span className="font-semibold">₹ {viewInv.subtotal?.toLocaleString()}</span></div>
                <div className="flex justify-between text-sm"><span className="text-slate-500">Tax ({viewInv.taxRate}%)</span><span className="font-semibold">₹ {viewInv.taxAmount?.toLocaleString()}</span></div>
                {viewInv.discount > 0 && <div className="flex justify-between text-sm"><span className="text-slate-500">Discount</span><span className="font-semibold text-emerald-600">-₹ {viewInv.discount?.toLocaleString()}</span></div>}
                <div className="flex justify-between text-base pt-2 border-t border-slate-200"><span className="font-bold">Grand Total</span><span className="font-bold text-primary-600 text-lg">₹ {viewInv.grandTotal?.toLocaleString()}</span></div>
              </div>
            </div>

            {/* Actions */}
            <div className="flex items-center justify-between p-6 border-t border-slate-100 bg-slate-50/50">
              <div className="flex gap-2">
                <button onClick={() => handleDownload(viewInv)} className="flex items-center gap-2 px-4 py-2.5 bg-white border border-slate-200 rounded-xl text-sm font-medium text-slate-600 hover:bg-slate-50"><Download className="w-4 h-4" />Download</button>
                <button onClick={() => handleDelete(viewInv._id)} className="flex items-center gap-2 px-4 py-2.5 bg-white border border-red-200 rounded-xl text-sm font-medium text-red-500 hover:bg-red-50"><Trash2 className="w-4 h-4" />Delete</button>
              </div>
              {viewInv.status !== 'paid' && (
                <button onClick={() => handleMarkPaid(viewInv._id)} className="flex items-center gap-2 px-6 py-2.5 bg-emerald-600 text-white rounded-xl text-sm font-bold hover:bg-emerald-700"><CheckCircle className="w-4 h-4" />Mark as Paid</button>
              )}
            </div>
          </div>
        </div>
      </>)}
    </div>
  );
};

export default Invoices;
